<a href="https://colab.research.google.com/github/Dywlanz/CPE-311/blob/main/Seatwork_6_1_Exploratory_Data_Analysis_on_Your_Own_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CPE311 Computational Thinking with Python

Name: Dejoras, Dylan James N.

Section: CPE22S3

Performed on: 03/11/2024
<br>
Submitted on: 03/11/2024<br>
Submitted to: Engr. Roman M. Richard

Instructions:

* Choose your own dataset from public repositories.
* Link your chosen dataset in this spreadsheet: Dataset SpreadsheetLinks to an external site.
* Perform simple exploratory data analysis using descriptive statistics.
* Employ the same steps as done in the hands-on activity and provide your own analysis of the dataset.
* Your submission must include your GitHub folder link that includes a customized readme file, Python Notebook Files, Dataset, and a simple presentation of your findings.

Note:

* Graphing is not required but may be done for additional points.

In [15]:
filepath = '/content/StudentsPerformance.csv'

In [16]:
import pandas as pd
import numpy as np
import statistics

In [17]:
df = pd.read_csv(filepath)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [18]:
# column names
for col in df.columns:
  print(col)

gender
race/ethnicity
parental level of education
lunch
test preparation course
math score
reading score
writing score

In [19]:
# data types of columns
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [21]:
# total number of students
len(df)

1000

In [22]:
# first 20 students
df.head(20)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61

In [23]:
# last 20 students
df.tail(20)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
980,female,group B,high school,free/reduced,none,8,24,23
981,male,group D,some high school,standard,none,81,78,78
982,male,group B,some high school,standard,completed,79,85,86
983,female,group A,some college,standard,completed,78,87,91
984,female,group C,some high school,standard,none,74,75,82
985,male,group A,high school,standard,none,57,51,54
986,female,group C,associate's degree,standard,none,40,59,51
987,male,group E,some high school,standard,completed,81,75,76
988,female,group A,some high school,free/reduced,none,44,45,45
989,female,group D,some college,free/reduced,completed,67,86,83
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [28]:
# created a dataframe to check the table for prepared students

column = 'test preparation course'
value = ['completed']

checker = df[column].isin(value) # .isin() is also a function for checking if a column
                                   # has a certain value

prepared = df[checker]

prepared

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [36]:
# number of prepared students
print(len(prepared), 'students are prepared')

358 students are prepared

In [29]:
# created a dataframe to check the table for unprepared students

column = 'test preparation course'
value = ['none']

checker = df[column].isin(value) # .isin() is also a function for checking if a column
                                   # has a certain value

unprepared = df[checker]

unprepared

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55
999,female,group D,some college,free/reduced,none,77,86,86

In [33]:
# number of prepared students
print(len(unprepared), 'students are not prepared')

642 students are not prepared

In [70]:
# created a dataframe to check the number of students who passed math

column = 'math score'
# we assume that 70 is the passing score
min_value = 70
max_value = 100

checker = df[column].between(min_value, max_value) # .between() function for checking between two certain integers

passed_math = df[checker]

passed_math

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
984,female,group C,some high school,standard,none,74,75,82
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [71]:
len(passed_math)

409

In [73]:
# create dataframe to see how many who prepared and passed math

column = 'math score'
# we assume that 70 is the passing score
min_value = 70
max_value = 100

checker = prepared[column].between(min_value, max_value) # .between() function for checking between two certain integers

p_passed_math = prepared[checker]

p_passed_math

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
6,female,group B,some college,standard,completed,88,95,92
13,male,group A,some college,standard,completed,78,72,70
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
35,male,group E,associate's degree,standard,completed,81,81,79
38,female,group D,associate's degree,free/reduced,completed,75,90,88
...,...,...,...,...,...,...,...,...
982,male,group B,some high school,standard,completed,79,85,86
983,female,group A,some college,standard,completed,78,87,91
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

In [74]:
len(p_passed_math)

176

In [78]:
# create dataframe to see how many who did not prepared and passed math

column = 'math score'
# we assume that 70 is the passing score
min_value = 70
max_value = 100

checker = unprepared[column].between(min_value, max_value) # .between() function for checking between two certain integers

u_passed_math = unprepared[checker]

u_passed_math

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
16,male,group C,high school,standard,none,88,89,86
...,...,...,...,...,...,...,...,...
970,female,group D,bachelor's degree,standard,none,89,100,100
979,female,group C,associate's degree,standard,none,91,95,94
981,male,group D,some high school,standard,none,81,78,78
984,female,group C,some high school,standard,none,74,75,82
999,female,group D,some college,free/reduced,none,77,86,86

In [83]:
len(u_passed_math)

233

In [84]:
# 10. create dataframe to see how many passed reading

column = 'reading score'
# we assume that 70 is the passing score
min_value = 70
max_value = 100

checker = df[column].between(min_value, max_value) # .between() function for checking between two certain integers

passed_reading = df[checker]

passed_reading

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [85]:
len(passed_reading)

513

In [86]:
# 10. create dataframe to see how many passed writing

column = 'writing score'
# we assume that 70 is the passing score
min_value = 70
max_value = 100

checker = df[column].between(min_value, max_value) # .between() function for checking between two certain integers

passed_writing = df[checker]

passed_writing

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [87]:
len(passed_writing)

489

In [88]:
# 10. Create a new dataframe "Pedia" that gathers data with age 0 to 19

column = 'writing score'
min_value = 71
max_value = 100

checker = df[column].between(min_value, max_value) # .between() function for checking between two certain integers

passed_writing = df[checker]
# there is no one under the age of 20 so it will return an empty dataframe
passed_writing

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [90]:
# create dataframe to see how many females passed math

column = 'gender'
value = ['female']

checker = passed_math[column].isin(value) # .isin() is also a function for checking if a column
                                   # has a certain value

f_passed_math = passed_math[checker]

f_passed_math

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
36,female,group D,associate's degree,standard,none,74,81,83
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
983,female,group A,some college,standard,completed,78,87,91
984,female,group C,some high school,standard,none,74,75,82
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [91]:
len(f_passed_math)

178

In [92]:
# create dataframe to see how many males passed math

column = 'gender'
value = ['male']

checker = passed_math[column].isin(value) # .isin() is also a function for checking if a column
                                   # has a certain value

m_passed_math = passed_math[checker]

m_passed_math

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,76,78,75
13,male,group A,some college,standard,completed,78,72,70
16,male,group C,high school,standard,none,88,89,86
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
...,...,...,...,...,...,...,...,...
971,male,group C,some high school,standard,completed,78,72,69
981,male,group D,some high school,standard,none,81,78,78
982,male,group B,some high school,standard,completed,79,85,86
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75

In [93]:
len(m_passed_math)

231

In [94]:
# create dataframe to see number of females

column = 'gender'
value = ['female']

checker = df[column].isin(value) # .isin() is also a function for checking if a column
                                   # has a certain value

female = df[checker]

female

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [95]:
len(female)

518

In [96]:
# create dataframe to see number of males

column = 'gender'
value = ['male']

checker = df[column].isin(value) # .isin() is also a function for checking if a column
                                   # has a certain value

male = df[checker]

male

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
10,male,group C,associate's degree,standard,none,58,54,52
...,...,...,...,...,...,...,...,...
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55

In [97]:
len(male)

482

In [99]:
# get average score of males and females in math
print("Average score of females in math:", np.mean(female['math score'])) # np.mean() for average
print("Average score of males in math:", np.mean(male['math score']))

Average score of females in math: 63.633204633204635
Average score of males in math: 68.72821576763485

In [98]:
# get median score of males and females in math
print("Median of math score of females:", np.median(female['math score'])) # np.mean() for average
print("Median of math score of males:", np.median(male['math score']))

Median of math score of females: 65.0
Median of math score of males: 69.0

In [100]:
# get median score of males and females in math
print("Standard deviation of math score of females:", np.std(female['math score'])) # np.mean() for average
print("Standard deviation of math score of males:", np.std(male['math score']))

Standard deviation of math score of females: 15.4764928784033
Standard deviation of math score of males: 14.341377060332784